spring:
  application:
    name: msvc-gateway
  eureka:
    client:
      register-with-eureka: false
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
        routes:
          - id: doctor
            uri: http://localhost:8090
            predicates:
              - Path=/api/doctor/**
          - id: patient
            uri: http://localhost:9090
            predicates:
              - Path=/api/patient/**